forge 'forge.puppetlabs.com'

# Forge Modules
mod 'puppetlabs/ntp', '4.1.0'
mod 'puppetlabs/stdlib'
mod 'puppetlabs-aws', '2.1.0'
mod 'puppetlabs-concat', '5.3.0'
mod 'crayfishx-hiera_http', '3.4.0'
mod 'herculesteam-augeasproviders', '2.2.1'
mod 'herculesteam-augeasproviders_apache', '3.1.1'
mod 'herculesteam-augeasproviders_base', '2.1.0'
mod 'herculesteam-augeasproviders_core', '2.4.0'
mod 'herculesteam-augeasproviders_grub', '3.1.0'
mod 'herculesteam-augeasproviders_mounttab', '2.1.1'
mod 'herculesteam-augeasproviders_nagios', '2.1.1'
mod 'herculesteam-augeasproviders_pam', '2.2.1'
mod 'herculesteam-augeasproviders_ssh', '3.2.1'
mod 'puppetlabs-inifile', '2.5.0'
mod 'puppetlabs-lvm', '1.2.0'
mod 'puppetlabs-mount_providers', '2.0.1'
